### ISSUE TITLE
pythongremlin errors

### ISSUE THREAD

**Issue by esdesai** [awslabs/amazon-neptune-tools#134]
When trying to connect to Neptune, getting the following error:

TypeError: 'LazyHttpHeaders' object is not iterable

----- Sample code below ---
from neptune_python_utils.gremlin_utils import GremlinUtils

GremlinUtils.init_statics(globals())

gremlin_utils = GremlinUtils()

conn = gremlin_utils.remote_connection()
g = gremlin_utils.traversal_source(connection=conn)

print(g.V().limit(10).valueMap().toList())

conn.close()

**Comment by beebs-systap** [comment]
@krlawrence Any ideas on this one?

**Comment by akash-github-projects** [comment]
Hey, any updates on this one?

**Comment by domjancik** [comment]
Hi all, also ran into this when testing with the Gremlin / Python samples provided here https://docs.aws.amazon.com/neptune/latest/userguide/get-started-cfn-lambda.html

I assume it might be a version mismatch between the libraries here and what these utils were designed for.

But in any case, the fix is fairly simple and should retain the lazy nature of the headers, which I would again assume is there so the contents are fresh for each request.

Add the following lines to the `LazyHttpHeaders` class in `endpoints.py` to make the object iterable:

``` python
    def __iter__(self):
        return iter(self.items())
```

This will generate the headers and return their built-in iterator.

The full class then becomes

``` python
class LazyHttpHeaders:
    
    def __init__(self, lazy_headers):
        self.lazy_headers = lazy_headers
    
    def get_all(self) -> Iterable[Tuple[str, str]]:
        return self.items()
        
    def items(self):
        return self.lazy_headers().items()
        
    def __iter__(self):
        return iter(self.items())
```

For reference: https://www.w3schools.com/python/python_iterators.asp

**Comment by iansrobinson** [comment]
Thank you @domjancik for identifying the issue and proposing the fix – and pointing out that the Lambda CFN provided one way of testing. I was able to reproduce in a Lambda created by the CFN, and then incorporate the fix: https://github.com/awslabs/amazon-neptune-tools/pull/143

**Comment by domjancik** [comment]
Following up on this, while not exactly related to the original issue, we've had some problems with `LazyHttpHeaders` again when downgrading`gremlinpython` version to `3.5.6` due to some compatibility constraints.

This version tries to directly write headers, so the following error comes up:

```
LazyHttpHeaders' object does not support item assignment
```

In context:
```
{
    "levelname": "ERROR",
    "exc_info": "(<class 'TypeError'>, TypeError(\"'LazyHttpHeaders' object does not support item assignment\"), <traceback object at 0x7fd94083bcc0>)",
    "location": "gremlin_utils.py remote_connection:79",
    "message": "Failed to connect to Neptune.",
    "traceback": [
        "  File \"/var/task/functions/common/db/neptune_python_utils/gremlin_utils.py\", line 64, in remote_connection\n    connection = DriverRemoteConnection(\n",
        "  File \"/opt/python/gremlin_python/driver/driver_remote_connection.py\", line 67, in __init__\n    self._client = client.Client(url, traversal_source,\n",
        "  File \"/opt/python/gremlin_python/driver/client.py\", line 95, in __init__\n    self._fill_pool()\n",
        "  File \"/opt/python/gremlin_python/driver/client.py\", line 111, in _fill_pool\n    conn = self._get_connection()\n",
        "  File \"/opt/python/gremlin_python/driver/client.py\", line 145, in _get_connection\n    return connection.Connection(\n",
        "  File \"/opt/python/gremlin_python/driver/connection.py\", line 44, in __init__\n    self._headers[useragent.userAgentHeader] = useragent.userAgent\n"
    ]
}
```

Fix here is to allow some extra headers to be written using the `__setitem__` python data model method:

```python
class LazyHttpHeaders:
    def __init__(self, lazy_headers):
        self.lazy_headers = lazy_headers
        self.extra_headers = {}

    def get_all(self) -> Iterable[Tuple[str, str]]:
        return self.items()

    def items(self):
        combined_headers = {**self.lazy_headers(), **self.extra_headers}
        return combined_headers.items()

    def __iter__(self):
        return iter(self.items())

    def __setitem__(self, key, value):
        self.extra_headers[key] = value
```
