### ISSUE TITLE
Add vertex label to Neptune stream records when a vp is updated

### ISSUE THREAD

**Issue by esidialy** [awslabs/amazon-neptune-tools#234]
Add vertex label to the stream record when a vertex property is updated 
```
{
  "id": "an ID string",
  "label": "vertex label"   #suggested property to be added
  "type": "vp",
  "key": "the property name",
  "value": {
    "value": "the new value of the node property",
    "dataType": "the datatype of the node property"
  }
}
```

**Comment by triggan** [comment]
Thank you for your request.  I will forward this to our product managers.  As Neptune Streams is a production feature of Neptune and not one of the opensource utilities in this repository, I am going to close this out.

In the meantime, if you need such functionality you may want to build vertex/edge IDs that also include the vertex/edge label.  Ex:  Instead of `3ae78bc` use `label-3ae78bc` and then parse the label out in your stream consumer code.
