### ISSUE TITLE
IAM authentication enabled on Neptune

### ISSUE THREAD

**Issue by FitnessTrackerIOS** [awslabs/amazon-neptune-tools#46]
Hello, 
I was able to use this if IAM auth is not enabled on Neptune , But if it is enabled can glue-neptune handle that ? any plans to include that option ? or any other way to authenticate via glue if enabled.

Thank you.

**Comment by iansrobinson** [comment]
Hi @FitnessTrackerIOS 

Glue-neptune doesn't work with IAM DB Auth enabled at the moment, but I appreciate it is important for many use cases.

I'll look into adding support – however, because of prior commitments, I may not be able to begin work on this feature for a couple of weeks.

Apologies for the delay.

Kind regards

ian

**Comment by FitnessTrackerIOS** [comment]
Thank you for your response, we will be definitely waiting for this feature to be done. I will check back with you in a couple of weeks, also one more question any plans to upgrade glue-neptune to python 3 ?

**Comment by iansrobinson** [comment]
Yes - I'll upgrade to Python 3 at the same time. Good reminder - thank you.

**Comment by FitnessTrackerIOS** [comment]
Awesome Thank you !!

**Comment by iansrobinson** [comment]
Hi @FitnessTrackerIOS 

I've implemented IAM DB Auth for connecting to Neptune from Glue jobs, and updated to Python 3 - but in a new module:

https://github.com/awslabs/amazon-neptune-tools/tree/master/neptune-python-utils

I created a new module because I wanted to take the opportunity to add in some features from previous work, and thereby create a more general purpose Neptune client utility.

The glue-neptune classes have been renamed slightly:

GremlinCsvTransforms -> GlueGremlinCsvTransforms
NeptuneConnectionInfo -> GlueNeptuneConnectionInfo
NeptuneGremlinClient -> GlueGremlinClient

There's a working demo of replicating Amazon Aurora MySQL data to Amazon Neptune using AWS Glue that incorporates neptune-python-utils here:

https://github.com/aws-samples/amazon-neptune-samples/tree/master/gremlin/glue-neptune

Kind regards

ian




Therefore, I've deprecated

**Comment by FitnessTrackerIOS** [comment]
Thank you Rob !! This is helpfull.
