### ISSUE TITLE
RE: MemoryLimitExceededException while export neptune data.

### ISSUE THREAD

**Issue by SivaVijayakumar** [awslabs/amazon-neptune-tools#60]
when I try to export a user-defined query, I am getting below error. 

Query:
bin/neptune-export.sh export-pg-from-queries -e neptunedbcluster-xxxxxxxxxxxx.cluster-yyyyyyyyyyyy.us-east-1.neptune.amazonaws.com -d /home/ec2-user/output -q tapestryVisitMetadataVertex="g.V().hasLabel('tapestryVisitMetaData').order().by('lastVisitedDate').limit(20).valueMap(true)" --concurrency 4

Error:
{"requestId":"50474e09-c5d6-43bd-9e67-e98ec8855b88","code":"MemoryLimitExceededException","detailedMessage":"Query cannot be completed due to memory limitations."}

Kindly help me on this issue.

**Comment by iansrobinson** [comment]
Hi @SivaVijayakumar This error is occurring on the Neptune side. Your query is looking for all vertices with a tapestryVisitMetaData label, and then ordering these vertices by lastVisitedDate. If there are a lot of tapestryVisitMetaData vertices, bringing them all into memory to order them may trigger this issue. Could you perhaps add a has() step before the order() step that limits vertices to a certain date range before ordering them? Something like:

```
g.V().
  hasLabel('tapestryVisitMetaData').
  has('lastVisitedDate', gt(datetime('2020-03-01'))).
  order().by('lastVisitedDate').
  limit(20).
  valueMap(true)
```
Note also that the `--concurrency 4` paremeter will have no effect here, because you only have one query in your tapestryVisitMetadataVertex named group to execute. This query will be executed on a single thread, not distributed across 4 threads.

**Comment by triggan** [comment]
As mentioned above, this issue has to do with the query being submitted to Neptune by the neptune-export service.  For aggregation queries such as those that do ordering, there's no way to parallelize these for neptune-export to use multiple client threads.  Closing this issue, but feel free to re-open if you feel the response is insufficient.
